### ISSUE TITLE
Minor issue not showing application name

### ISSUE THREAD

**Issue by mhoogenbosch** [jimmyeao/TEAMS2HA#56]
When hovering over the icon on taskbar the icon doens't show the name:

![image](https://github.com/jimmyeao/TEAMS2HA/assets/36899598/c3b985af-3954-41ee-a4fc-ad1291eb9a8d)

**Comment by jimmyeao** [comment]
So this looks like a bug in one of the libraries we are using (Hardecodet.NotifyIcon) - when I enable tooltips on windows 11, they appear in the top left of the screen instead of over the icon :/
https://github.com/hardcodet/wpf-notifyicon/issues/106
waiting for them to merge a PR so I can update the library
